# Generated by Django 5.1.1 on 2024-10-02 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+1234567890". Up to 15 digits allowed.', regex='^\\+\\d{10,15}$')]),
        ),
    ]
