# Generated by Django 5.1.1 on 2024-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
    ]
